### ISSUE TITLE
flutter: Http status error [400]

### ISSUE THREAD

**Issue by alanjholiveira** [weldonsouza/cielo_ecommerce#1]
Amigo ao usar o app de example apresenta flutter: Http status error [400]

**Comment by weldonsouza** [comment]
> Amigo ao usar o app de example apresenta flutter: Http status error [400]

Você preencher os campos merchantId: "SEU_MERCHANT_ID" e merchantKey: "SEU_MERCHANT_KEY" ?

**Comment by alanjholiveira** [comment]
> > Amigo ao usar o app de example apresenta flutter: Http status error [400]
> 
> Você preencher os campos merchantId: "SEU_MERCHANT_ID" e merchantKey: "SEU_MERCHANT_KEY" ?

Fiz o preenchimento normal do  (SEU_MERCHANT_ID e SEU_MERCHANT_KEY)

**Comment by weldonsouza** [comment]
> > > Amigo ao usar o app de example apresenta flutter: Http status error [400]
> > 
> > 
> > Você preencher os campos merchantId: "SEU_MERCHANT_ID" e merchantKey: "SEU_MERCHANT_KEY" ?
> 
> Fiz o preenchimento normal do (SEU_MERCHANT_ID e SEU_MERCHANT_KEY)

Preciso de mais informações para poder identificar, qual foi o button utilizado na primeira chamada? Já testou o merchantId: e merchantKey Postman?

**Comment by alanjholiveira** [comment]
Resolvido.

Estava usando merchantId e merchantKey de produção em modo SANDBOX (DEV)

Obrigado!
